### ISSUE TITLE
Incorrect Eatery status past midnight if Eatery is open past midnight

### ISSUE THREAD

**Issue by dantheli** [cuappdev/DiningStack#3]
If an eatery is open past midnight, incorrect status when the clock passes midnight.

For instance, if Nasties is open to 2:00 AM and it's currently 12:10 AM, isOpenNow() returns false.

**Comment by say25** [comment]
Issue stems from intended backend behavior. Fixed in issue will be fixed with Eatery issue "Eateries with Events Ending after Midnight Appear Closed" #121

**Comment by say25** [comment]
Actually was a DiningStack issue closed with commit  f72a916
